version: '3.8'

services:
  profile-site:
    image: ghcr.io/khoirony/tensorflow-js:latest
    container_name: tensorflow-js-app
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.profile.rule=Host(`tensorflow.khoirony.fun`)"
      - "traefik.http.routers.profile.entrypoints=web,websecure"
      - "traefik.http.routers.profile.tls=true"
      - "traefik.http.routers.profile.tls.certresolver=mytlschallenge"

networks:
  traefik_proxy:
    name: root_default
    external: true