version: '3.8'

services:
  profile-site:
    image: ghcr.io/khoirony/tensorflow-js:latest
    container_name: tensorflow-js-app
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tensorflow.rule=Host(`tensorflow.khoirony.fun`)"
      - "traefik.http.routers.tensorflow.entrypoints=web,websecure"
      - "traefik.http.routers.tensorflow.tls=true"
      - "traefik.http.routers.tensorflow.tls.certresolver=mytlschallenge"
      # Tambahkan label ini untuk menautkan router ke service secara eksplisit
      - "traefik.http.services.tensorflow.loadbalancer.server.port=80" 
      - "traefik.http.routers.tensorflow.service=tensorflow"

networks:
  traefik_proxy:
    name: root_default
    external: true